import { Inter } from "next/font/google";
import "./globals.css";
import SideNavBar from "./navbar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BD Doctors24",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-cyan-100">
        {children}
        </body>
    </html>
  );
}
